---
title: "Test"
author: "Cody York"
date: "2023-06-19"
output: html_document
---

```{r}
library(tidyr)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(plotly)

setwd('C:/Users/cy_su/PycharmProjects/DSCI_605_Data_Visualizations/Module 5/M5_Lab4/')

data <- read.csv("Fouryears_all.csv")

data$Date <- ymd_hms(data$Date)

start_date <- as.Date("2019-09-01")
end_date <- as.Date("2021-09-01")
filtered_data <- data %>%
  filter(Date >= start_date & Date <= end_date & Primary.Type == "BATTERY")

data_hourly <- filtered_data %>%
  mutate(Hour = floor_date(Date, "hour")) %>%
  group_by(Hour) %>%
  summarise(Count = n()) %>%
  ungroup()

plot <- ggplot(data = data_hourly, aes(x = Hour, y = Count)) +
  geom_line(aes(color = "Count"), size = 1.2, linetype = "solid") +
  geom_point(size = 2, color = "blue") +
  scale_x_datetime(date_labels = "%Y-%m-%d", date_breaks = "1 day") +
  labs(x = "Time",
       y = "Count",
       title = "Two-Year Time Series Visualization",
       caption = "Source: Your Data Source") +
  theme_minimal() +
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(size = 12),
        plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
        plot.caption = element_text(size = 8),
        legend.position = "bottom",
        panel.grid.major = element_line(color = "gray", size = 0.1),
        panel.grid.minor = element_line(color = "gray", size = 0.05))

plotly_plot <- ggplotly(plot)

plotly_plot

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
